# Generated by Django 4.2.11 on 2024-03-29 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=30, null=True)),
                ("user_id", models.CharField(blank=True, max_length=30, null=True)),
                ("message", models.CharField(blank=True, max_length=300, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
            ],
        ),
    ]
