# Generated by Django 4.2.11 on 2024-03-29 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ("date_field", models.DateField(auto_now_add=True, null=True)),
                ("time_field", models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="messages",
            name="user_name",
        ),
        migrations.AddField(
            model_name="messages",
            name="date_field",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="messages",
            name="time_field",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="messages",
            name="note_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="node.notebook",
            ),
        ),
    ]
