# Generated by Django 4.1.1 on 2024-03-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0002_notebook_remove_messages_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
