# Generated by Django 4.1.1 on 2024-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0003_alter_messages_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="user_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
