# Generated by Django 4.1.1 on 2024-03-29 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0005_alter_messages_user_id_alter_notebook_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="last_name",
        ),
    ]
