# Generated by Django 4.1.1 on 2024-03-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0007_transactions_stocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stocks",
            name="valuation",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transactions",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
    ]
