# Generated by Django 4.1.1 on 2024-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0008_stocks_price_stocks_valuation_transactions_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocks",
            name="user_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
