# Generated by Django 4.1.1 on 2024-03-29 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0010_rename_price_stocks_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocks",
            name="total_price",
        ),
    ]
