# Generated by Django 4.1.1 on 2024-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0011_remove_stocks_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("SYSTEM", "SYSTEM"), ("USER", "USER")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="type",
            field=models.CharField(
                choices=[("SELL", "SELL"), ("BUY", "BUY")], max_length=20
            ),
        ),
    ]
